spring.application.name=gdpr-user-portal-api

# DATABASE (MOCK LOCALE)
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=cefladb_iot;encrypt=false;
spring.datasource.username=sa
spring.datasource.password=Password123!
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# Evita che Spring modifichi le tabelle esistenti
spring.jpa.hibernate.ddl-auto=none
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

spring.jpa.show-sql=true