services:
  sqlserver:
    image: mcr.microsoft.com/azure-sql-edge:latest
    container_name: sqlserver-mock
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Password123!
    volumes:
      - ./init-mock.sql:/init-mock.sql
